# Generated by Django 3.2.4 on 2021-06-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('handle', models.CharField(max_length=100)),
                ('published_scope', models.CharField(max_length=30)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_graphql_api_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('sku', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.IntegerField()),
                ('inventory_policy', models.CharField(max_length=30)),
                ('fulfillment_service', models.CharField(max_length=30)),
                ('option1', models.CharField(blank=True, max_length=30, null=True)),
                ('option2', models.CharField(blank=True, max_length=30, null=True)),
                ('option3', models.CharField(blank=True, max_length=30, null=True)),
                ('image_id', models.CharField(blank=True, max_length=100, null=True)),
                ('taxable', models.BooleanField()),
                ('barcode', models.CharField(blank=True, max_length=30, null=True)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('inventory_item_id', models.CharField(max_length=30)),
                ('inventory_quantity', models.IntegerField()),
                ('old_inventory_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.product')),
            ],
        ),
    ]
