# Generated by Django 3.2.4 on 2021-06-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
